---
- ignore: {name: Replace case with fromMaybe, within: [Ty]}

- fixity: infixr 3 &&&
- fixity: infixr 6 <#>
- fixity: infixr 1 <=<
- fixity: infixr 5 @~
- fixity: infixr 6 @>
- fixity: infixr 6 @@
