cabal-version:      2.2
name:               pizarnik
version:            0.1.0.0
synopsis:           Pizarnik stack-based concatenative language
description:
    Pizarnik is a stack-based, concatenative language with extensible cases handled properly by drawing inspiration from linear logic.

license:            AGPL-3.0-or-later
license-file:       LICENSE
author:             Vanessa McHale
maintainer:         vamchale@gmail.com
category:           Language
build-type:         Simple
extra-doc-files:    CHANGELOG.md
extra-source-files:
    lib/*.piz
    prelude/*.piz
    test/data/*.piz
    test/examples/*.piz

source-repository head
    type:     git
    location: https://github.com/vmchale/pizarnik

common warnings
    default-language:   Haskell2010
    default-extensions: OverloadedStrings
    ghc-options:
        -Wall -Wincomplete-uni-patterns -Wincomplete-record-updates
        -Wredundant-constraints -Widentities -Wcpp-undef
        -Wmissing-export-lists -Wunused-packages -Wno-missing-signatures
        -Wno-x-partial -Wno-operator-whitespace-ext-conflict

library
    import:             warnings
    exposed-modules:
        Dbg
        A
        L
        P
        Parse
        Pr
        S
        Ty

    other-modules:
        B
        C
        E
        Imp
        M
        Nm
        Nm.Map
        Nm.Set
        R
        TS
        Ty.Clone

    other-extensions:
        DeriveFunctor
        RankNTypes

    build-tool-depends:
        , alex:alex
        , happy:happy  >=2.1

    ghc-options:        -fmax-pmcheck-models=50
    build-depends:
        , array
        , base           >=4.19.0.0
        , bytestring
        , containers     >=0.6.2.1
        , directory
        , filepath
        , microlens      >=0.4.0.0
        , mtl
        , prettyprinter  >=1.7.0
        , text
        , transformers

    hs-source-dirs:     src

executable pc
    import:         warnings
    hs-source-dirs: run
    main-is:        X.hs
    other-modules:  REPL
    build-depends:
        , base
        , bytestring
        , containers
        , directory
        , filepath
        , haskeline
        , optparse-applicative
        , pizarnik
        , prettyprinter
        , text
        , transformers

test-suite pizarnik-test
    import:           warnings
    other-extensions: OverloadedStrings
    type:             exitcode-stdio-1.0
    hs-source-dirs:   test
    main-is:          Z.hs
    ghc-options:      -threaded -rtsopts "-with-rtsopts=-N -k1k"
    build-depends:
        , base
        , pizarnik
        , tasty
        , tasty-hunit
        , transformers

benchmark pizarnik-bench
    import:         warnings
    type:           exitcode-stdio-1.0
    hs-source-dirs: bench
    main-is:        Bench.hs
    build-depends:
        , base
        , criterion
        , pizarnik
        , transformers
